[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "rsbin"
version = "0.5.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
serde = { version = "^1.0.82", features = ["derive"] }
sha1 = "0.10.1"
toml = "^0.5.0"
