[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "rsbin"
version = "0.5.0"

[dependencies]
failure = "^0.1.1"
rust-crypto = "^0.2.36"
serde = "^1.0.0"
serde_derive = "^1.0.0"
toml = "^0.4.0"
