[package]
name = "rsbin"
version = "0.4.0"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]

[dependencies]
error-chain = "^0.10.0"
rust-crypto = "^0.2.36"
serde = "^1.0.0"
serde_derive = "^1.0.0"
toml = "^0.4.0"
