[package]
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
name = "rsbin"
version = "0.5.0"

[dependencies]
failure = "^0.1.2"
rust-crypto = "^0.2.36"
serde = { version = "^1.0.82", features = ["derive"] }
toml = "^0.5.0"
